//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.DATIC.SistemaHorasConsulta.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackXCita
    {
        public int IdCita { get; set; }
        public bool Estado { get; set; }
        public string RespuestaPregunta1 { get; set; }
        public string RespuestaPregunta2 { get; set; }
        public string RespuestaPregunta3 { get; set; }
        public string ComentarioAdicional { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
