//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.DATIC.SistemaHorasConsulta.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaHorasConsultaEntities : DbContext
    {
        public SistemaHorasConsultaEntities()
            : base("name=SistemaHorasConsultaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Lugare> Lugares { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<Tematica> Tematicas { get; set; }
        public virtual DbSet<CitaXEstudiante> CitaXEstudiantes { get; set; }
        public virtual DbSet<FeedbackXCita> FeedbackXCitas { get; set; }
    
        public virtual int Pr_Cita_Eliminar(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Cita_Eliminar", idCitaParameter);
        }
    
        public virtual int Pr_Cita_Insertar(Nullable<int> idProfesor, Nullable<int> idEstudiante, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> horaInicio)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("IdEstudiante", idEstudiante) :
                new ObjectParameter("IdEstudiante", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Cita_Insertar", idProfesorParameter, idEstudianteParameter, fechaParameter, horaInicioParameter);
        }
    
        public virtual ObjectResult<Pr_Citas_Consultar_Result> Pr_Citas_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Citas_Consultar_Result>("Pr_Citas_Consultar");
        }
    
        public virtual int Pr_Citas_Eliminar(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Citas_Eliminar", idCitaParameter);
        }
    
        public virtual ObjectResult<Pr_CitasFiltrarFecha_Consultar_Result> Pr_CitasFiltrarFecha_Consultar(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitasFiltrarFecha_Consultar_Result>("Pr_CitasFiltrarFecha_Consultar", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<Pr_CitasXEstudiante_Consultar_Result> Pr_CitasXEstudiante_Consultar(Nullable<int> idEstudiante)
        {
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("IdEstudiante", idEstudiante) :
                new ObjectParameter("IdEstudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitasXEstudiante_Consultar_Result>("Pr_CitasXEstudiante_Consultar", idEstudianteParameter);
        }
    
        public virtual ObjectResult<Pr_CitaXProfesor_Consultar_Result> Pr_CitaXProfesor_Consultar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitaXProfesor_Consultar_Result>("Pr_CitaXProfesor_Consultar", idProfesorParameter);
        }
    
        public virtual ObjectResult<Pr_DiasCita_Consultar_Result> Pr_DiasCita_Consultar(string dia)
        {
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DiasCita_Consultar_Result>("Pr_DiasCita_Consultar", diaParameter);
        }
    
        public virtual int Pr_Horario_Editar(Nullable<int> idHorario, string dia, Nullable<System.TimeSpan> horaInicio, Nullable<System.TimeSpan> horaFinal)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            var horaFinalParameter = horaFinal.HasValue ?
                new ObjectParameter("HoraFinal", horaFinal) :
                new ObjectParameter("HoraFinal", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Editar", idHorarioParameter, diaParameter, horaInicioParameter, horaFinalParameter);
        }
    
        public virtual int Pr_Horario_Eliminar(Nullable<int> idHorario)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Eliminar", idHorarioParameter);
        }
    
        public virtual int Pr_Horario_Insertar(string dia, Nullable<System.TimeSpan> horaInicio, Nullable<System.TimeSpan> horaFinal)
        {
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            var horaFinalParameter = horaFinal.HasValue ?
                new ObjectParameter("HoraFinal", horaFinal) :
                new ObjectParameter("HoraFinal", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Insertar", diaParameter, horaInicioParameter, horaFinalParameter);
        }
    
        public virtual ObjectResult<Pr_HorarioProfesor_Consultar_Result> Pr_HorarioProfesor_Consultar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_HorarioProfesor_Consultar_Result>("Pr_HorarioProfesor_Consultar", idProfesorParameter);
        }
    
        public virtual int Pr_HorarioXProfesor_Insertar(Nullable<int> idHorario, Nullable<int> idProfesor)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_HorarioXProfesor_Insertar", idHorarioParameter, idProfesorParameter);
        }
    
        public virtual int Pr_Lugar_Editar(Nullable<int> idLugar, string nombre)
        {
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Editar", idLugarParameter, nombreParameter);
        }
    
        public virtual int Pr_Lugar_Eliminar(Nullable<int> idLugar)
        {
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Eliminar", idLugarParameter);
        }
    
        public virtual int Pr_Lugar_Insertar(string nombreLugar)
        {
            var nombreLugarParameter = nombreLugar != null ?
                new ObjectParameter("NombreLugar", nombreLugar) :
                new ObjectParameter("NombreLugar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Insertar", nombreLugarParameter);
        }
    
        public virtual int Pr_Tematica_Editar(Nullable<int> idTematica, string nombre, string descripcion)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Editar", idTematicaParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int Pr_Tematica_Eliminar(Nullable<int> idTematica)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Eliminar", idTematicaParameter);
        }
    
        public virtual int Pr_Tematica_Insertar(string nombreTematica, string descripcion)
        {
            var nombreTematicaParameter = nombreTematica != null ?
                new ObjectParameter("NombreTematica", nombreTematica) :
                new ObjectParameter("NombreTematica", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Insertar", nombreTematicaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Pr_Tematicas_Consultar_Result> Pr_Tematicas_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Tematicas_Consultar_Result>("Pr_Tematicas_Consultar");
        }
    
        public virtual ObjectResult<Pr_TematicasProfesor_Consultar_Result> Pr_TematicasProfesor_Consultar(Nullable<int> idTematica)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_TematicasProfesor_Consultar_Result>("Pr_TematicasProfesor_Consultar", idTematicaParameter);
        }
    
        public virtual int Pr_TematicaXProfesor_Insertar(Nullable<int> idTematica, Nullable<int> idProfesor)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_TematicaXProfesor_Insertar", idTematicaParameter, idProfesorParameter);
        }
    }
}
