//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCR.DATIC.SistemaHorasConsulta.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaHorasConsultaEntities : DbContext
    {
        public SistemaHorasConsultaEntities()
            : base("name=SistemaHorasConsultaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Horario> Horarios { get; set; }
        public virtual DbSet<Lugare> Lugares { get; set; }
        public virtual DbSet<Profesore> Profesores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tematica> Tematicas { get; set; }
        public virtual DbSet<Administradore> Administradores { get; set; }
        public virtual DbSet<CitaXEstudiante> CitaXEstudiantes { get; set; }
        public virtual DbSet<FeedbackXCita> FeedbackXCitas { get; set; }
        public virtual DbSet<TematicaXProfesor> TematicaXProfesors { get; set; }
    
        public virtual int Pr_Administador_Editar(string usuarioActual, string usuarioNuevo)
        {
            var usuarioActualParameter = usuarioActual != null ?
                new ObjectParameter("UsuarioActual", usuarioActual) :
                new ObjectParameter("UsuarioActual", typeof(string));
    
            var usuarioNuevoParameter = usuarioNuevo != null ?
                new ObjectParameter("UsuarioNuevo", usuarioNuevo) :
                new ObjectParameter("UsuarioNuevo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Administador_Editar", usuarioActualParameter, usuarioNuevoParameter);
        }
    
        public virtual int Pr_Administador_Eliminar(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Administador_Eliminar", usuarioParameter);
        }
    
        public virtual ObjectResult<string> Pr_Administadores_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pr_Administadores_Consultar");
        }
    
        public virtual int Pr_Administadores_Insertar(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Administadores_Insertar", usuarioParameter);
        }
    
        public virtual int Pr_Cita_Cancelar(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Cita_Cancelar", idCitaParameter);
        }
    
        public virtual int Pr_Cita_Insertar(Nullable<int> idProfesor, Nullable<int> idEstudiante, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> horaInicio)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("IdEstudiante", idEstudiante) :
                new ObjectParameter("IdEstudiante", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Cita_Insertar", idProfesorParameter, idEstudianteParameter, fechaParameter, horaInicioParameter);
        }
    
        public virtual int Pr_CitaRealizada_Editar(Nullable<int> idCita)
        {
            var idCitaParameter = idCita.HasValue ?
                new ObjectParameter("IdCita", idCita) :
                new ObjectParameter("IdCita", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_CitaRealizada_Editar", idCitaParameter);
        }
    
        public virtual ObjectResult<Pr_Citas_Consultar_Result> Pr_Citas_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Citas_Consultar_Result>("Pr_Citas_Consultar");
        }
    
        public virtual ObjectResult<Pr_CitasFiltrarFecha_Consultar_Result> Pr_CitasFiltrarFecha_Consultar(Nullable<System.DateTime> fecha1, Nullable<System.DateTime> fecha2)
        {
            var fecha1Parameter = fecha1.HasValue ?
                new ObjectParameter("Fecha1", fecha1) :
                new ObjectParameter("Fecha1", typeof(System.DateTime));
    
            var fecha2Parameter = fecha2.HasValue ?
                new ObjectParameter("Fecha2", fecha2) :
                new ObjectParameter("Fecha2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitasFiltrarFecha_Consultar_Result>("Pr_CitasFiltrarFecha_Consultar", fecha1Parameter, fecha2Parameter);
        }
    
        public virtual ObjectResult<Pr_CitasXEstudiante_Consultar_Result> Pr_CitasXEstudiante_Consultar(Nullable<int> idEstudiante)
        {
            var idEstudianteParameter = idEstudiante.HasValue ?
                new ObjectParameter("IdEstudiante", idEstudiante) :
                new ObjectParameter("IdEstudiante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitasXEstudiante_Consultar_Result>("Pr_CitasXEstudiante_Consultar", idEstudianteParameter);
        }
    
        public virtual ObjectResult<Pr_CitaXProfesor_Consultar_Result> Pr_CitaXProfesor_Consultar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_CitaXProfesor_Consultar_Result>("Pr_CitaXProfesor_Consultar", idProfesorParameter);
        }
    
        public virtual ObjectResult<Pr_DiasCita_Consultar_Result> Pr_DiasCita_Consultar(string dia)
        {
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_DiasCita_Consultar_Result>("Pr_DiasCita_Consultar", diaParameter);
        }
    
        public virtual int Pr_Horario_Editar(Nullable<int> idHorario, string dia, Nullable<System.TimeSpan> horaInicio, Nullable<System.TimeSpan> horaFinal)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            var horaFinalParameter = horaFinal.HasValue ?
                new ObjectParameter("HoraFinal", horaFinal) :
                new ObjectParameter("HoraFinal", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Editar", idHorarioParameter, diaParameter, horaInicioParameter, horaFinalParameter);
        }
    
        public virtual int Pr_Horario_Eliminar(Nullable<int> idHorario)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Eliminar", idHorarioParameter);
        }
    
        public virtual int Pr_Horario_Insertar(string dia, Nullable<System.TimeSpan> horaInicio, Nullable<System.TimeSpan> horaFinal)
        {
            var diaParameter = dia != null ?
                new ObjectParameter("Dia", dia) :
                new ObjectParameter("Dia", typeof(string));
    
            var horaInicioParameter = horaInicio.HasValue ?
                new ObjectParameter("HoraInicio", horaInicio) :
                new ObjectParameter("HoraInicio", typeof(System.TimeSpan));
    
            var horaFinalParameter = horaFinal.HasValue ?
                new ObjectParameter("HoraFinal", horaFinal) :
                new ObjectParameter("HoraFinal", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Horario_Insertar", diaParameter, horaInicioParameter, horaFinalParameter);
        }
    
        public virtual ObjectResult<Pr_HorarioProfesor_Consultar_Result> Pr_HorarioProfesor_Consultar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_HorarioProfesor_Consultar_Result>("Pr_HorarioProfesor_Consultar", idProfesorParameter);
        }
    
        public virtual ObjectResult<Pr_Horarios_Consultar_Result> Pr_Horarios_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Horarios_Consultar_Result>("Pr_Horarios_Consultar");
        }
    
        public virtual int Pr_HorarioXProfesor_Editar(Nullable<int> idHorarioActual, Nullable<int> idProfesorActual, Nullable<int> idHorarioNuevo, Nullable<int> idProfesorNuevo)
        {
            var idHorarioActualParameter = idHorarioActual.HasValue ?
                new ObjectParameter("IdHorarioActual", idHorarioActual) :
                new ObjectParameter("IdHorarioActual", typeof(int));
    
            var idProfesorActualParameter = idProfesorActual.HasValue ?
                new ObjectParameter("IdProfesorActual", idProfesorActual) :
                new ObjectParameter("IdProfesorActual", typeof(int));
    
            var idHorarioNuevoParameter = idHorarioNuevo.HasValue ?
                new ObjectParameter("IdHorarioNuevo", idHorarioNuevo) :
                new ObjectParameter("IdHorarioNuevo", typeof(int));
    
            var idProfesorNuevoParameter = idProfesorNuevo.HasValue ?
                new ObjectParameter("IdProfesorNuevo", idProfesorNuevo) :
                new ObjectParameter("IdProfesorNuevo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_HorarioXProfesor_Editar", idHorarioActualParameter, idProfesorActualParameter, idHorarioNuevoParameter, idProfesorNuevoParameter);
        }
    
        public virtual int Pr_HorarioXProfesor_Eliminar(Nullable<int> idHorario, Nullable<int> idProfesor)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_HorarioXProfesor_Eliminar", idHorarioParameter, idProfesorParameter);
        }
    
        public virtual int Pr_HorarioXProfesor_Insertar(Nullable<int> idHorario, Nullable<int> idProfesor)
        {
            var idHorarioParameter = idHorario.HasValue ?
                new ObjectParameter("IdHorario", idHorario) :
                new ObjectParameter("IdHorario", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_HorarioXProfesor_Insertar", idHorarioParameter, idProfesorParameter);
        }
    
        public virtual int Pr_Lugar_Editar(Nullable<int> idLugar, string nombre)
        {
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Editar", idLugarParameter, nombreParameter);
        }
    
        public virtual int Pr_Lugar_Eliminar(Nullable<int> idLugar)
        {
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Eliminar", idLugarParameter);
        }
    
        public virtual int Pr_Lugar_Insertar(string nombreLugar)
        {
            var nombreLugarParameter = nombreLugar != null ?
                new ObjectParameter("NombreLugar", nombreLugar) :
                new ObjectParameter("NombreLugar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Lugar_Insertar", nombreLugarParameter);
        }
    
        public virtual ObjectResult<Pr_Lugares_Consultar_Result> Pr_Lugares_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Lugares_Consultar_Result>("Pr_Lugares_Consultar");
        }
    
        public virtual int Pr_Profesor_Editar(Nullable<int> idProfesor, string nombre, string primerApellido, string segundoApellido, string usuario, string correoElectronico, Nullable<int> idLugar, byte[] foto)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Profesor_Editar", idProfesorParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, usuarioParameter, correoElectronicoParameter, idLugarParameter, fotoParameter);
        }
    
        public virtual int Pr_Profesor_Eliminar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Profesor_Eliminar", idProfesorParameter);
        }
    
        public virtual ObjectResult<Pr_Profesores_Consultar_Result> Pr_Profesores_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Profesores_Consultar_Result>("Pr_Profesores_Consultar");
        }
    
        public virtual int Pr_Profesores_Insertar(string nombre, string primerApellido, string segundoApellido, string usuario, string correoElectronico, Nullable<int> idLugar, byte[] foto)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var correoElectronicoParameter = correoElectronico != null ?
                new ObjectParameter("CorreoElectronico", correoElectronico) :
                new ObjectParameter("CorreoElectronico", typeof(string));
    
            var idLugarParameter = idLugar.HasValue ?
                new ObjectParameter("IdLugar", idLugar) :
                new ObjectParameter("IdLugar", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("Foto", foto) :
                new ObjectParameter("Foto", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Profesores_Insertar", nombreParameter, primerApellidoParameter, segundoApellidoParameter, usuarioParameter, correoElectronicoParameter, idLugarParameter, fotoParameter);
        }
    
        public virtual ObjectResult<Pr_ProfesoresXTematica_Consultar_Result> Pr_ProfesoresXTematica_Consultar(Nullable<int> idTematica)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_ProfesoresXTematica_Consultar_Result>("Pr_ProfesoresXTematica_Consultar", idTematicaParameter);
        }
    
        public virtual int Pr_Tematica_Editar(Nullable<int> idTematica, string nombre, string descripcion)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Editar", idTematicaParameter, nombreParameter, descripcionParameter);
        }
    
        public virtual int Pr_Tematica_Eliminar(Nullable<int> idTematica)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Eliminar", idTematicaParameter);
        }
    
        public virtual int Pr_Tematica_Insertar(string nombreTematica, string descripcion)
        {
            var nombreTematicaParameter = nombreTematica != null ?
                new ObjectParameter("NombreTematica", nombreTematica) :
                new ObjectParameter("NombreTematica", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Tematica_Insertar", nombreTematicaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<Pr_Tematicas_Consultar_Result> Pr_Tematicas_Consultar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_Tematicas_Consultar_Result>("Pr_Tematicas_Consultar");
        }
    
        public virtual ObjectResult<Pr_TematicasXProfesor_Consultar_Result> Pr_TematicasXProfesor_Consultar(Nullable<int> idProfesor)
        {
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pr_TematicasXProfesor_Consultar_Result>("Pr_TematicasXProfesor_Consultar", idProfesorParameter);
        }
    
        public virtual int Pr_TematicaXProfesor_Editar(Nullable<int> idTematicaActual, Nullable<int> idProfesorActual, Nullable<int> idTematicaNueva, Nullable<int> idProfesorNuevo, string especialidadesNuevo)
        {
            var idTematicaActualParameter = idTematicaActual.HasValue ?
                new ObjectParameter("IdTematicaActual", idTematicaActual) :
                new ObjectParameter("IdTematicaActual", typeof(int));
    
            var idProfesorActualParameter = idProfesorActual.HasValue ?
                new ObjectParameter("IdProfesorActual", idProfesorActual) :
                new ObjectParameter("IdProfesorActual", typeof(int));
    
            var idTematicaNuevaParameter = idTematicaNueva.HasValue ?
                new ObjectParameter("IdTematicaNueva", idTematicaNueva) :
                new ObjectParameter("IdTematicaNueva", typeof(int));
    
            var idProfesorNuevoParameter = idProfesorNuevo.HasValue ?
                new ObjectParameter("IdProfesorNuevo", idProfesorNuevo) :
                new ObjectParameter("IdProfesorNuevo", typeof(int));
    
            var especialidadesNuevoParameter = especialidadesNuevo != null ?
                new ObjectParameter("EspecialidadesNuevo", especialidadesNuevo) :
                new ObjectParameter("EspecialidadesNuevo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_TematicaXProfesor_Editar", idTematicaActualParameter, idProfesorActualParameter, idTematicaNuevaParameter, idProfesorNuevoParameter, especialidadesNuevoParameter);
        }
    
        public virtual int Pr_TematicaXProfesor_Eliminar(Nullable<int> idTematica, Nullable<int> idProfesor)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_TematicaXProfesor_Eliminar", idTematicaParameter, idProfesorParameter);
        }
    
        public virtual int Pr_TematicaXProfesor_Insertar(Nullable<int> idTematica, Nullable<int> idProfesor, string especialidades)
        {
            var idTematicaParameter = idTematica.HasValue ?
                new ObjectParameter("IdTematica", idTematica) :
                new ObjectParameter("IdTematica", typeof(int));
    
            var idProfesorParameter = idProfesor.HasValue ?
                new ObjectParameter("IdProfesor", idProfesor) :
                new ObjectParameter("IdProfesor", typeof(int));
    
            var especialidadesParameter = especialidades != null ?
                new ObjectParameter("Especialidades", especialidades) :
                new ObjectParameter("Especialidades", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_TematicaXProfesor_Insertar", idTematicaParameter, idProfesorParameter, especialidadesParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
