//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Consultas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor_schedule
    {
        public int id_professor { get; set; }
        public int id_schedule { get; set; }
        public byte[] availability { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
